# Site settings
locale: "en-US"
title: "Milele Hallingquest"
name: "AI Automation"
description: "AI Automation Engineer | Building intelligent workflows that save time & drive ROI"
url: "https://mhallingquest.github.io"   # your GitHub Pages URL
baseurl: ""                              # no trailing slash
repository: "mhallingquest/mhallingquest.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"  # "default", "air", "contrast", "dark", "mint"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Author
author:
  name: "Milele Hallin"
  avatar: "/assets/img/avatar.jpg"   # add an image or remove this line
  bio: "I build AI-powered automations that transform manual workflows into intelligent systems."
  location: "Remote / NYC"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mhallingquest"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:milelehallingquest@gmail.com"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# Navigation (header)
nav:
  - title: "Projects"
    url: "/projects/"
  - title: "Automation"
    url: "/automation/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "mailto:milelehallingquest@gmail.com"

# Collections (optional for case studies)
collections:
  case_studies:
    output: true
    permalink: /case-studies/:path/

# Exclusions
exclude:
  - README.md
